namespace Medalion.Data.Domain;

/// <summary>
/// Represents a trading strategy/algorithm
/// </summary>
public class Strategy : BaseEntity
{
    /// <summary>
    /// Strategy name
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Strategy description
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Strategy type (e.g., "MeanReversion", "Momentum", "Arbitrage", "VolatilityBased")
    /// </summary>
    public string StrategyType { get; set; } = string.Empty;

    /// <summary>
    /// Strategy version
    /// </summary>
    public string Version { get; set; } = "1.0.0";

    /// <summary>
    /// Whether the strategy is currently active
    /// </summary>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Whether the strategy is in backtesting mode
    /// </summary>
    public bool IsBacktesting { get; set; } = false;

    /// <summary>
    /// Strategy configuration (JSON)
    /// </summary>
    public string Configuration { get; set; } = "{}";

    /// <summary>
    /// Risk parameters (JSON)
    /// </summary>
    public string RiskParameters { get; set; } = "{}";

    /// <summary>
    /// Maximum position size
    /// </summary>
    public decimal? MaxPositionSize { get; set; }

    /// <summary>
    /// Maximum loss per trade
    /// </summary>
    public decimal? MaxLossPerTrade { get; set; }

    /// <summary>
    /// Maximum daily loss
    /// </summary>
    public decimal? MaxDailyLoss { get; set; }

    /// <summary>
    /// Strategy performance metrics (JSON)
    /// </summary>
    public string? PerformanceMetrics { get; set; }

    /// <summary>
    /// Last execution timestamp
    /// </summary>
    public DateTime? LastExecutedAt { get; set; }

    // Navigation properties
    public ICollection<TradingSignal> Signals { get; set; } = new List<TradingSignal>();
    public ICollection<Trade> Trades { get; set; } = new List<Trade>();
}

/// <summary>
/// Represents a trading signal generated by a strategy
/// </summary>
public class TradingSignal : BaseEntity
{
    /// <summary>
    /// Reference to the strategy that generated this signal
    /// </summary>
    public Guid StrategyId { get; set; }

    /// <summary>
    /// Asset ID (if trading stocks/crypto)
    /// </summary>
    public Guid? AssetId { get; set; }

    /// <summary>
    /// Polymarket Event ID (if trading on Polymarket)
    /// </summary>
    public Guid? PolymarketEventId { get; set; }

    /// <summary>
    /// Signal type: BUY, SELL, HOLD
    /// </summary>
    public SignalType SignalType { get; set; }

    /// <summary>
    /// Signal strength/confidence (0-100)
    /// </summary>
    public decimal Confidence { get; set; }

    /// <summary>
    /// Signal timestamp
    /// </summary>
    public DateTime SignalTimestamp { get; set; }

    /// <summary>
    /// Target price
    /// </summary>
    public decimal? TargetPrice { get; set; }

    /// <summary>
    /// Stop loss price
    /// </summary>
    public decimal? StopLoss { get; set; }

    /// <summary>
    /// Take profit price
    /// </summary>
    public decimal? TakeProfit { get; set; }

    /// <summary>
    /// Suggested position size
    /// </summary>
    public decimal? SuggestedQuantity { get; set; }

    /// <summary>
    /// Signal source data (JSON) - contains the Alpaca/Polymarket data that triggered the signal
    /// </summary>
    public string SourceData { get; set; } = "{}";

    /// <summary>
    /// Whether the signal was acted upon
    /// </summary>
    public bool WasActedUpon { get; set; } = false;

    /// <summary>
    /// Signal expiration time
    /// </summary>
    public DateTime? ExpiresAt { get; set; }

    /// <summary>
    /// Additional metadata (JSON)
    /// </summary>
    public string? Metadata { get; set; }

    // Navigation properties
    public Strategy Strategy { get; set; } = null!;
    public Asset? Asset { get; set; }
    public PolymarketEventData? PolymarketEvent { get; set; }
    public ICollection<Trade> Trades { get; set; } = new List<Trade>();
}

/// <summary>
/// Signal type enumeration
/// </summary>
public enum SignalType
{
    Buy = 1,
    Sell = 2,
    Hold = 3,
    StrongBuy = 4,
    StrongSell = 5
}
